apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-parcelize'

apply plugin: 'kotlin-kapt'

apply plugin: "androidx.navigation.safeargs.kotlin"

configurations {
    compile.exclude group: 'commons-logging'
}

android {
    namespace "com.Azhe.ghs.gshschedule"
    compileSdkVersion 34
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    defaultConfig {
        applicationId "com.Azhe.ghs.gshschedule"
        minSdkVersion 24
        targetSdkVersion 34
        versionCode 103
        versionName "1.0.3_beta"
        resValue "string", "app_name", "GSH课程表"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        ndk {
            abiFilters 'armeabi-v7a', "arm64-v8a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFile 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
        compose true
    }

    kapt {
        correctErrorTypes true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = '1.5.8'
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/ASL2.0'
        exclude('org/apache/commons/codec/language/bm/*.txt')
        exclude 'lib/*/libRSSupport.so'
        exclude 'lib/*/librsjni.so'
        exclude 'lib/*/librsjni_androidx.so'
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "GSH课程表_v${variant.versionName}.apk"
        }
        // 打包后自动复制 APK 到指定目录（可按需修改或注释）
        /*
        variant.assemble.doLast {
            copy {
                from variant.outputs*.outputFile
                into file("output")
            }
        }
        */
    }
}

dependencies {
    def lifecycle_version = "2.7.0"
    def room_version = "2.6.1"

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'com.google.android.material:material:1.11.0'
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.github.GrenderG:Toasty:1.5.2'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'cn.carbswang.android:NumberPickerView:1.2.0'
    implementation('com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.0-beta11') {
        exclude group: 'androidx'
    }
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    kapt 'com.github.bumptech.glide:compiler:4.16.0'
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
    implementation 'com.github.doyaaaaaken:kotlin-csv-jvm:1.9.0'
    implementation 'com.github.jahirfiquitiva:TextDrawable:1.0.3'
    implementation 'com.bigkoo:quicksidebar:1.0.3'
    implementation 'com.timehop.stickyheadersrecyclerview:library:0.4.3@aar'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation('net.sf.biweekly:biweekly:0.6.3') {
        exclude module: 'jackson-core'
        exclude group: 'com.fasterxml.jackson.core'
    }
    implementation 'com.github.sephiroth74:android-target-tooltip:2.0.4'

    // Compose
    implementation platform("androidx.compose:compose-bom:$compose_bom_version")
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.activity:activity-compose:1.8.2'
    implementation 'androidx.compose.runtime:runtime-livedata'
    debugImplementation 'androidx.compose.ui:ui-tooling'
}
